# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-16 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Create_at', models.DateTimeField(auto_now_add=True)),
                ('Name', models.CharField(max_length=5000)),
                ('Age', models.CharField(max_length=5000)),
                ('Address', models.CharField(max_length=5000)),
                ('Email', models.CharField(max_length=5000)),
                ('Phone_Number', models.CharField(max_length=5000)),
                ('Do_you_like_open_source_software', models.CharField(max_length=5000)),
                ('Python_level', models.CharField(max_length=5000)),
                ('C_level', models.CharField(max_length=5000)),
                ('Cpp_level', models.CharField(max_length=5000)),
                ('Java_level', models.CharField(max_length=5000)),
                ('JavaScript_level', models.CharField(max_length=5000)),
                ('Which_computer_language_are_you_prefer', models.CharField(max_length=5000)),
            ],
            options={
                'ordering': ['-Create_at'],
            },
        ),
    ]
