# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-20 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('Question_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Create_at', models.DateTimeField(auto_now_add=True)),
                ('Question_description', models.CharField(max_length=5000)),
            ],
            options={
                'ordering': ['-Create_at'],
            },
        ),
    ]
