# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-20 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_questions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='Address',
            new_name='Question_10Answer',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='Age',
            new_name='Question_11Answer',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='C_level',
            new_name='Question_12Answer',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='Cpp_level',
            new_name='Question_1Answer',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='Do_you_like_open_source_software',
            new_name='Question_2Answer',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='Email',
            new_name='Question_3Answer',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='JavaScript_level',
            new_name='Question_4Answer',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='Java_level',
            new_name='Question_5Answer',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='Name',
            new_name='Question_6Answer',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='Phone_Number',
            new_name='Question_7Answer',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='Python_level',
            new_name='Question_8Answer',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='Which_computer_language_are_you_prefer',
            new_name='Question_9Answer',
        ),
    ]
