# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-20 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_auto_20180120_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaire',
            old_name='Question_10Answer',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='Question_11Answer',
            new_name='Age',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='Question_12Answer',
            new_name='C_level',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='Question_1Answer',
            new_name='Cpp_level',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='Question_2Answer',
            new_name='Do_you_like_open_source_software',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='Question_4Answer',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='Question_3Answer',
            new_name='JavaScript_level',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='Question_5Answer',
            new_name='Java_level',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='Question_6Answer',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='Question_7Answer',
            new_name='Phone_Number',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='Question_8Answer',
            new_name='Python_level',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='Question_9Answer',
            new_name='Which_computer_language_are_you_prefer',
        ),
    ]
