# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-21 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('Question_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Question_Create_at', models.DateTimeField(auto_now_add=True)),
                ('Question_1', models.CharField(max_length=5000)),
                ('Question_2', models.CharField(max_length=5000)),
                ('Question_3', models.CharField(max_length=5000)),
                ('Question_4', models.CharField(max_length=5000)),
                ('Question_5', models.CharField(max_length=5000)),
                ('Question_6', models.CharField(max_length=5000)),
                ('Question_7', models.CharField(max_length=5000)),
                ('Question_8', models.CharField(max_length=5000)),
                ('Question_9', models.CharField(max_length=5000)),
                ('Question_10', models.CharField(max_length=5000)),
                ('Question_11', models.CharField(max_length=5000)),
                ('Question_12', models.CharField(max_length=5000)),
            ],
            options={
                'ordering': ['-Question_Create_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='questionnaire',
            options={'ordering': ['-Answer_Create_at']},
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='Address',
            new_name='Answer_1',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='Age',
            new_name='Answer_10',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='C_level',
            new_name='Answer_11',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='Cpp_level',
            new_name='Answer_12',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='Do_you_like_open_source_software',
            new_name='Answer_2',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='Email',
            new_name='Answer_3',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='JavaScript_level',
            new_name='Answer_4',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='Java_level',
            new_name='Answer_5',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='Name',
            new_name='Answer_6',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='Phone_Number',
            new_name='Answer_7',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='Python_level',
            new_name='Answer_8',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='Which_computer_language_are_you_prefer',
            new_name='Answer_9',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='Create_at',
            new_name='Answer_Create_at',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='Id',
            new_name='Answer_Id',
        ),
    ]
